// 캐릭터 표와 명단. 계산과 화면이 함께 쓰는 순수한 자료다.
export const INFO = {
  iceman: { name: '얼음장수', kind: '괴롭히는 패', color: '#59c8ff', speed: 5.5, top: 4.3, hp: 3, atk: 1, score: '18점', origin: '아비터의 무한 스테이시스',
    skill: '앞쪽 넓은 범위를 5초간 얼립니다. 언 사람은 깨지지 않는 얼음덩어리가 되어 길까지 막습니다.',
    how: '스페이스. 내 앞 9칸 지점이 중심입니다.', counter: '얼어 있는 동안은 맞지 않습니다. 풀리면 10초간 보복 피해가 2배입니다.' },
  parking: { name: '주차 단속', kind: '괴롭히는 패', color: '#3b7bff', speed: 5.5, top: 4.0, hp: 3, atk: 1, score: '17점', origin: '고스트의 락다운(기계에만 통함)',
    skill: '앞에 있는 바퀴 달린 캐릭터 하나를 12초간 세웁니다. 세워진 사람은 맞아도 피하지 못합니다.',
    how: '스페이스. 얼음장수, 납치범, 스포츠카, 로동로봇, 대박 화물에게만 통합니다.', counter: '바퀴가 없는 캐릭터에게는 안 통합니다.' },
  exile: { name: '유배', kind: '괴롭히는 패', color: '#b3202a', speed: 4.6, top: 4.4, hp: 4, atk: 2, score: '9점', origin: '워크3판 세종, 리콜',
    skill: '지금 1등을 1구간 맨 처음으로 보냅니다. 거리 제한이 없습니다.',
    how: '스페이스. 다시 쓰려면 20초를 기다립니다.', counter: '1등이 아니면 안 맞습니다. 흐엉에게는 안 통합니다.' },
  van: { name: '납치범', kind: '괴롭히는 패', color: '#1f9f96', speed: 6, top: 4.6, hp: 6, atk: 1, score: '8점', origin: '스타2판 특수전 수송선',
    skill: '가까운 캐릭터를 태우고 달립니다. 다리 위에서 내리면 떨어져 죽고, 결승선을 같이 넘으면 태운 사람도 골인합니다.',
    how: '스페이스로 태우고, 다시 눌러 내립니다. 6초가 지나면 저절로 내립니다.', counter: '납치범이 죽으면 풀려납니다.' },
  snail: { name: '달팽이', kind: '괴롭히는 패', color: '#b7c95a', speed: 3.2, top: 5.0, hp: 3, atk: 0, score: '7점', origin: '스타2판 모선핵',
    skill: '지금 1등을 5초간 느리게 합니다. 지나간 자리에는 점액이 남아 밟으면 느려집니다.',
    how: '스페이스. 점액은 저절로 남습니다.', counter: '점액이 없는 줄로 피해 가세요.' },
  swap: { name: '자리 바꿔', kind: '움직이는 패', color: '#ff9a3d', speed: 5, top: 3.9, hp: 1, atk: 0, score: '6점', origin: '스타2판 니아드라',
    skill: '앞사람과 자리를 맞바꿉니다. 체력이 1이라 한 대 맞으면 죽습니다.',
    how: '스페이스. 내 앞에서 가장 가까운 사람이 대상입니다.', counter: '한 대만 치면 됩니다.' },
  copier: { name: '복사기', kind: '뒤섞는 패', color: '#7be495', speed: 4.8, top: 3.6, hp: 3, atk: 1, score: '6점', origin: '스타2판 예언자',
    skill: '가장 가까운 상대와 같은 캐릭터가 됩니다.',
    how: '스페이스. 좋은 패를 든 사람 옆에서 쓰세요.', counter: '꽝을 들고 옆에 붙으면 꽝을 복사해 갑니다.' },
  blink: { name: '축지법', kind: '움직이는 패', color: '#b8c7ff', speed: 4.2, top: 4.6, hp: 2, atk: 1, score: '5점', origin: '스타2판 추적자',
    skill: '앞으로 순간이동합니다. 사람과 장애물을 통과합니다.',
    how: '스페이스. 2.5초마다 쓸 수 있습니다.', counter: '체력이 낮습니다. 도착한 자리에서 치세요.' },
  builder: { name: '로동로봇', kind: '설치하는 패', color: '#f5b301', speed: 5, top: 4.6, hp: 5, atk: 2, score: '2점', origin: 'SCV의 배럭',
    skill: '가건물을 짓습니다. 길을 막고, 20초 동안 부서지지 않으면 30점을 받습니다. 캐릭터가 바뀌어도 점수는 지은 사람이 받습니다.',
    how: '스페이스. 내 바로 뒤에 지어집니다.', counter: '가건물을 공격해 부수세요.' },
  heuong: { name: '흐엉', kind: '꽝', color: '#8f84c8', speed: 1.6, top: 10, hp: Infinity, atk: 0, score: '95점', origin: '속업 안 된 대군주',
    skill: '무적입니다. 맞지도, 얼지도, 끌려가지도 않습니다. 대신 가장 느립니다.',
    how: '그냥 가세요. 골인만 하면 95점입니다.', counter: '막을 방법은 판 엎기 같은 점수 초기화뿐입니다.' },
  boulder: { name: '짱돌', kind: '꽝', color: '#9aa0ad', speed: 2.4, top: 3.4, hp: 1, atk: 99, rate: 2, score: '4점', origin: '스타2판 집정관',
    skill: '한 대 치면 누구든 죽습니다. 하지만 엄청 느리고 체력이 1입니다.',
    how: 'F로 공격합니다. 한 번 치면 2초를 쉽니다.', counter: '다가오기 전에 먼저 치세요.' },
  sportscar: { name: '빠를 거 같냐?', kind: '꽝', color: '#d81e2c', speed: 2.6, top: 2.2, hp: 4, atk: 1, score: '3점', origin: '일반 벌처',
    skill: '생긴 것과 달리 느립니다. 장애물에 부딪히면 끼어서 못 움직입니다.',
    how: '끼면 A와 D를 번갈아 네 번 누르세요.', counter: '앞에 장애물을 두면 끼입니다.' },
  rent: { name: '월세', kind: '꽝', color: '#d1202a', speed: 4.4, top: 3.9, hp: 4, atk: 0, score: '0점', origin: '초당 감점 유닛',
    skill: '살아 있는 동안 2초마다 1점씩 깎입니다. 공격도 못 합니다.',
    how: '빨리 골인하거나, 누가 죽여주길 기다리세요.', counter: '굳이 죽여주지 마세요.' },
  reset: { name: '리셋 버튼', kind: '꽝', color: '#e02a2a', speed: 4.6, top: 3.2, hp: 6, atk: 0, score: '내 점수 0점', origin: '스캔티드',
    skill: '골인하면 내 점수가 0이 됩니다. 4구간에서는 결승선으로 끌려갑니다.',
    how: '4구간에 들어가기 전에 누군가에게 맞아 죽는 것이 살 길입니다.', counter: '죽여주지 않으면 됩니다.' },
  wallet: { name: '마이너스 통장', kind: '꽝', color: '#a86a3a', speed: 4.6, top: 4.4, hp: 3, atk: 0, score: '-10점', origin: '카카루',
    skill: '골인하면 10점이 깎입니다. 4구간에서는 결승선으로 끌려갑니다.',
    how: '4구간에 들어가기 전에 누군가에게 맞아 죽는 것이 살 길입니다.', counter: '죽여주지 않으면 됩니다.' },
  pot: { name: '안감^^', kind: '꽝', color: '#c8643c', speed: 0, top: 4.2, hp: 3, atk: 2, rate: 1, score: '없음', origin: '디바우러',
    skill: '못 움직입니다. 가까이 온 사람을 저절로 한 대씩 칩니다. 죽어야 바뀝니다.',
    how: '기다리세요. 30초가 지나면 저절로 바뀝니다.', counter: '멀리 돌아가거나, 죽이지 말고 그냥 두세요.' },
  jackpot: { name: '대박 화물', kind: '점수를 흔드는 패', color: '#ffcf5a', speed: 2.0, top: 4.6, hp: 1, atk: 0, score: '90점', origin: '4레인 전용 디파일러',
    skill: '골인하면 90점입니다. 4구간에서만 나오고, 체력이 1이라 한 대 맞으면 끝입니다.',
    how: '아무도 모르게 가세요.', counter: '한 대만 치면 됩니다.' },
  lotto: { name: '로또', kind: '점수를 흔드는 패', color: '#e63950', speed: 5, top: 5.8, hp: 3, atk: 1, score: '0 ~ 78점, 또는 0점으로', origin: '앨런 셰자르',
    skill: '골인할 때 추첨합니다. 0점에서 78점 사이가 더해지지만, 일곱 번에 한 번은 내 점수가 0이 됩니다.',
    how: '골인하세요.', counter: '골인하기 전에 죽이면 됩니다.' },
  hen: { name: '병아리 유치원', kind: '점수를 흔드는 패', color: '#ffd84d', speed: 3.4, top: 3.6, hp: 3, atk: 1, score: '남은 병아리 한 마리당 1점', origin: '캐리어와 인터셉터',
    skill: '병아리를 한 마리씩 앞으로 내보냅니다. 병아리가 결승선을 넘으면 2점입니다. 누구에게든 부딪히면 죽습니다.',
    how: '스페이스. 병아리는 다섯 마리입니다. 길이 뚫렸을 때 보내세요.', counter: '병아리 앞을 가로막으세요.' },
  eraser: { name: '지우개', kind: '점수를 흔드는 패', color: '#f29bb0', speed: 4.8, top: 3.4, hp: 3, atk: 0, score: '내 점수가 8점으로 고정', origin: '마젤란',
    skill: '닿은 캐릭터를 지웁니다. 지워진 사람은 죽은 것으로 칩니다.',
    how: '몸으로 들이받으세요.', counter: '닿지 않게 떨어져서 치세요.' },
  owl: { name: '부엉부엉', kind: '점수를 흔드는 패', color: '#b07a4a', speed: 4.4, top: 4.6, hp: 3, atk: 1, score: '6점', origin: '워크3판 부엉부엉',
    skill: '룰렛을 돌려 한 명을 죽입니다. 나도 걸릴 수 있습니다.',
    how: '스페이스.', counter: '운입니다.' },
  flipper: { name: '판 엎기', kind: '점수를 흔드는 패', color: '#ff7a45', speed: 4.5, top: 5.4, hp: 4, atk: 1, score: '전원 0점', origin: '히드라리스크',
    skill: '골인하면 모든 사람의 점수가 0이 됩니다.',
    how: '지고 있으면 골인하고, 이기고 있으면 죽어서 바꾸세요.', counter: '골인하기 전에 죽이세요.' },
  genki: { name: '원기옥', kind: '점수를 흔드는 패', color: '#7fd4ff', speed: 3.6, top: 7.2, hp: 2, atk: 0, score: '없음', origin: '과학 시설(원기옥 버전)',
    skill: '6초 동안 기를 모은 뒤 터뜨리면 나만 빼고 모두 죽습니다. 가건물도 부서집니다.',
    how: '스페이스. 모으는 동안 죽으면 끝입니다.', counter: '모으는 동안 치세요. 체력이 낮습니다.' },
  ghost: { name: '물귀신', kind: '점수를 흔드는 패', color: '#4fb8e8', speed: 4.8, top: 3.6, hp: 2, atk: 1, score: '나와 곁에 있던 전원 -7점', origin: '옵저버(물귀신)',
    skill: '골인할 때 가까이 있던 사람도 같이 7점이 깎입니다.',
    how: '사람들 곁에 붙어서 골인하세요.', counter: '물귀신이 결승선에 다가가면 멀리 떨어지세요.' },
  possess: { name: '빙의', kind: '괴롭히는 패', color: '#b06cff', speed: 4.6, top: 4.6, hp: 3, atk: 1, score: '6점', origin: '다크 아콘의 마인드 컨트롤',
    skill: '가까운 상대의 몸을 8초간 빼앗아 대신 조종합니다. 그 몸으로 골인하면 점수는 내가 받습니다. 그 몸의 능력도 내가 씁니다.',
    how: '스페이스. 그동안 내 원래 몸은 그 자리에 서 있어서 맞을 수 있습니다.', counter: '서 있는 무당의 몸을 치세요. 죽으면 풀립니다.' },
  bomber: { name: '폭탄 돌리기', kind: '설치하는 패', color: '#d43a3a', speed: 5, top: 4.6, hp: 3, atk: 1, score: '5점', origin: '워크3판 시한폭탄',
    skill: '가까운 사람에게 5초짜리 폭탄을 붙입니다. 폭탄은 몸이 닿으면 옮겨갑니다. 터지면 든 사람이 죽고 주변도 다칩니다.',
    how: '스페이스. 근처에 아무도 없으면 내가 들게 되니 얼른 남에게 비비세요.', counter: '폭탄이 붙으면 다른 사람에게 몸을 비비세요.' },
  cannon: { name: '대포집', kind: '설치하는 패', color: '#ff8a2a', speed: 4.2, top: 4.4, hp: 5, atk: 1, score: '4점', origin: '프로브의 포토 캐논 밭',
    skill: '포탑을 깝니다. 포탑은 25초 동안 지나가는 사람을 쏘고 길도 막습니다. 체력 낮은 캐릭터는 포탑밭을 못 지나갑니다.',
    how: '스페이스. 내 뒤에 놓입니다. 좁은 길에 여러 개 까세요.', counter: '포탑을 공격해 부수세요. 체력은 4입니다.' },
  draw: { name: '제비뽑기', kind: '뒤섞는 패', color: '#2fb8a8', speed: 4.8, top: 4.2, hp: 3, atk: 1, score: '6점', origin: '워크3판 제비뽑기',
    skill: '앞사람의 캐릭터를 강제로 다시 뽑게 합니다. 좋은 패를 든 사람에게는 날벼락이고, 꽝을 든 사람에게는 구원입니다.',
    how: '스페이스. 내 앞에서 가장 가까운 사람이 대상입니다.', counter: '꽝을 들었다면 제비뽑기 앞에 서 있으세요.' },
  homesick: { name: '집에 갈래', kind: '꽝', color: '#ffd84d', speed: 5, top: 3.2, hp: 3, atk: 0, score: '6점', origin: '디바우러·민간인의 강제 이동',
    skill: '고무줄이 계속 뒤로 잡아당깁니다. 가만히 있으면 뒤로 끌려갑니다.',
    how: '앞으로 가는 키를 누르고 있지 말고 연타하세요.', counter: '내버려 두면 알아서 뒤로 갑니다.' },
  dog: { name: '멍멍이', kind: '꽝', color: '#d9a05a', speed: 5.4, top: 3.0, hp: 2, atk: 1, score: '35점', origin: '라이나돈·벵갈라스',
    skill: '골인하면 35점이지만 말을 잘 안 듣습니다. 가만두면 제멋대로 돌아다니고, 조종해도 옆으로 샙니다.',
    how: '계속 방향을 잡아 주세요. 손을 떼면 뒤로도 갑니다.', counter: '체력이 2뿐입니다.' },
  piggy: { name: '돼지 저금통', kind: '꽝', color: '#ff9ec4', speed: 2.2, top: 3.0, hp: 12, atk: 0, score: '1점', origin: '스타2판 돼지',
    skill: '단단하고 느리고 아무것도 못 합니다. 능력 키를 30번 누르면 스스로 깨져서 다른 캐릭터가 됩니다. 흩어진 동전은 줍는 사람이 1점씩 가져갑니다.',
    how: '스페이스를 30번 연타하세요.', counter: '깨질 때 옆에 있다가 동전을 주우세요.' },
  liar: { name: '속았지', kind: '뒤섞는 패', color: '#ff9a3d', speed: 5.6, top: 5.2, hp: 3, atk: 1, score: '5점', origin: '저글링의 잠복 낚시',
    skill: '버튼에는 가속이라고 쓰여 있지만, 누르면 5초간 땅에 머리를 박고 못 움직입니다. 대신 그동안은 아무것도 안 맞습니다.',
    how: '스페이스. 얼음이나 폭탄을 피할 때만 쓰세요.', counter: '머리를 뺄 때까지 기다렸다가 치세요.' },
  mold: { name: '곰팡이', kind: '뒤섞는 패', color: '#7fbf4a', speed: 4.4, top: 3.0, hp: 2, atk: 0, score: '2점', origin: '퀸과 감염된 커맨드센터',
    skill: '남이 지은 가건물이나 포탑에 붙으면 걸어 다니는 건물이 됩니다. 그 건물로 골인하면 78점입니다.',
    how: '설치물 가까이에서 스페이스. 로동로봇이나 대포집이 있어야 쓸 수 있습니다.', counter: '설치물을 미리 부수거나, 걸어 다니는 건물을 잡으세요.' },
  moldhouse: { name: '걸어 다니는 건물', kind: '점수를 흔드는 패', color: '#c9722a', speed: 2.4, top: 5.4, hp: 8, atk: 0, special: true, score: '78점', origin: '감염된 커맨드센터',
    skill: '곰팡이가 설치물에 붙어 생깁니다. 느리지만 골인하면 78점입니다.',
    how: '뽑아서 나오지는 않습니다. 맞지 않게 조심해서 가세요.', counter: '여럿이 달려들어 잡으세요. 체력은 8입니다.' },
  ninja: { name: '분신술', kind: '뒤섞는 패', color: '#c7ccd6', speed: 5.6, top: 4.0, hp: 2, atk: 1, score: '6점', origin: '하이 템플러의 환상',
    skill: '가짜 셋을 만듭니다. 가짜는 길을 막고, 나를 노린 능력을 대신 맞아 줍니다.',
    how: '스페이스. 가짜는 10초 뒤 사라집니다.', counter: '가짜는 한 대 맞으면 터집니다.' },
  durian: { name: '두리안', kind: '장애물', special: true, color: '#a8b33c', speed: 0, top: 5.6, hp: 12, atk: 0, score: '없음', origin: '스타2판 파인애플',
    skill: '3구간 협곡을 통째로 막고 있습니다.',
    how: '조종하는 캐릭터가 아닙니다.', counter: '공격하거나 여럿이 밀어서 부수세요. 12초 뒤 다시 나타납니다.' },
};
// 키 큰 캐릭터가 앞사람을 가리지 않도록 뒷줄부터 키 순서로 세운다.
export const ROWS = [
  ['heuong', 'genki', 'lotto', 'durian', 'flipper', 'moldhouse', 'liar', 'snail', 'van'],
  ['builder', 'owl', 'jackpot', 'blink', 'possess', 'bomber', 'exile', 'wallet', 'cannon'],
  ['iceman', 'pot', 'draw', 'parking', 'ninja', 'swap', 'rent', 'copier', 'hen'],
  ['ghost', 'eraser', 'boulder', 'reset', 'homesick', 'dog', 'piggy', 'mold', 'sportscar'],
];
export const ROSTER = ROWS.flat();

// 자리 여덟 개의 기본 이름과 색. 첫 자리가 이 브라우저의 사람이고, 나머지는 봇이 채운다.
export const PLAYERS = [
  { name: '나', color: '#ffffff', you: true },
  { name: '번개발', color: '#ff4d4d' }, { name: '직진본능', color: '#2fe0c0' }, { name: '운빨러', color: '#b06cff' }, { name: '한방역전', color: '#ff9a3d' },
  { name: '느림보', color: '#ffd84d' }, { name: '거미손', color: '#5fe36a' }, { name: '째깍이', color: '#ff6fb5' },
];

// 버튼에 적을 능력 이름. 없는 캐릭터는 누르는 능력이 없다.
export const ACT = { iceman: '얼리기', parking: '딱지 붙이기', swap: '자리 바꾸기', blink: '축지', exile: '유배 보내기', van: '납치', copier: '복사', snail: '느려져라', owl: '룰렛 돌리기', genki: '터뜨리기', builder: '가건물 짓기', hen: '병아리 보내기', possess: '빙의', bomber: '폭탄 붙이기', cannon: '포탑 깔기', draw: '다시 뽑게 하기', liar: '가속', mold: '곰팡이 피우기', ninja: '분신술', piggy: '깨기' };
// 몸집(충돌 반지름). 적혀 있지 않으면 1.3이다.
export const SIZE = { cannon: 1.7, moldhouse: 1.9, dog: 1.2, piggy: 1.5, van: 1.8, jackpot: 1.9, sportscar: 1.7, boulder: 1.6, heuong: 1.4, hen: 1.5, genki: 1.6, iceman: 1.5 };
// 주차 단속에 걸리는, 바퀴 달린 캐릭터.
export const WHEELED = new Set(['iceman', 'van', 'sportscar', 'jackpot', 'builder']);
// 골인하면 받는 점수. 여기 없는 캐릭터는 저마다 다른 규칙을 따른다.
export const FIXED_GAIN = { possess: 6, bomber: 5, cannon: 4, draw: 6, homesick: 6, dog: 35, piggy: 1, liar: 5, mold: 2, moldhouse: 78, ninja: 6, iceman: 18, parking: 17, exile: 9, van: 8, snail: 7, swap: 6, copier: 6, blink: 5, builder: 2, heuong: 95, boulder: 4, sportscar: 3, rent: 0, wallet: -10, jackpot: 90, owl: 6, ghost: -7, genki: 0, pot: 0 };
// 뽑힐 확률의 배율. 판을 크게 흔드는 캐릭터는 원작처럼 드물게 나온다.
export const ODDS = { heuong: 0.4, jackpot: 0.5, pot: 0.5, genki: 0.5, flipper: 0.6 };
